npmScopes:
  mfrm:
    npmPublishRegistry: "https://projects-mfrm.pkgs.visualstudio.com/Mattress-Firm/_packaging/Registry/npm/registry"
    npmRegistryServer: "https://projects-mfrm.pkgs.visualstudio.com/Mattress-Firm/_packaging/Registry/npm/registry"

yarnPath: .yarn/releases/yarn-sources.cjs
